POST http://localhost:3333/subscriptions
Content-Type: application/json

{
    "name": "indicado3",
    "email": "indicado3@dac.unicamp.br",
    "referrer": "0523f648-0dec-4911-a427-d9c9317a963a"
}

###

GET http://localhost:3333/invites/278c174d-10ef-42ea-8562-e3015810d618

###

GET http://localhost:3333/subscribers/278c174d-10ef-42ea-8562-e3015810d618/ranking/clicks


###
GET http://localhost:3333/subscribers/278c174d-10ef-42ea-8562-e3015810d618/ranking/count
###
GET http://localhost:3333/subscribers/278c174d-10ef-42ea-8562-e3015810d618/ranking/position
###
GET http://localhost:3333/ranking
